version: '3.9'
services:

  prepare:
    image: alpine:3.17.3
    volumes:
      - .:/experiment:rw
      - ./scripts:/scripts:rw
    entrypoint: /bin/sh -c
    command: /scripts/create-folders.sh

  recreate-dataset:
    depends_on:
      prepare:
        condition: service_completed_successfully
    profiles:
      - create-data
    image: danysk/${PROJECT_NAME:-unknown}-create-dataset:${VERSION:-latest}
    build:
      dockerfile: ./docker/preprocess/Dockerfile
      context: .
    volumes:
      - ./PM10-data:/experiment/PM10-data
    command:
      - |
        /experiment/refine-locations.main.kts
        /experiment/download-all-PMD10-data.main.kts
        /experiment/cleanup-PMD10-data.main.kts
        mv /experiment/data-summary.json.zstd /experiment/PM10-summary/data-summary.json.zstd

  download-dataset:
    depends_on:
      prepare:
        condition: service_completed_successfully
    image: danysk/${PROJECT_NAME:-unknown}-download-dataset:${VERSION:-latest}
    build:
        dockerfile: ./docker/download/Dockerfile
        context: .
    volumes:
      - ./PM10-summary:/output:rw

  decompress-dataset:
    depends_on:
      download-dataset:
        condition: service_completed_successfully
    image: danysk/${PROJECT_NAME:-unknown}-decompress:${VERSION:-latest}
    build:
      dockerfile: ./docker/decompress/Dockerfile
      context: .
    volumes:
      - ./PM10-summary:/output:rw

  reduce-dataset:
    depends_on:
      decompress-dataset:
        condition: service_completed_successfully
    image: danysk/${PROJECT_NAME:-unknown}-reduce-dataset:${VERSION:-latest}
    build:
      dockerfile: ./docker/reduce/Dockerfile
      context: .
    volumes:
      - ./PM10-summary:/PM10-summary:rw
    profiles:
      - testing
    command: '/PM10-summary/data-summary.json /PM10-summary/data-summary.json'

  start-db:
    image: mongo:6.0
    init: true
    ports:
      - "27017:27017"
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 10s
      timeout: 5s
      retries: 3

  populate-db:
    depends_on:
      start-db:
        condition: service_healthy
#      reduce-dataset:
#        condition: service_completed_successfully
    image: mongo:6.0
    network_mode: host
    restart: "no"
    volumes:
      - ./PM10-summary:/PM10-summary
    command: /usr/bin/mongoimport --type json --collection pm10 --jsonArray --file /PM10-summary/data-summary.json

  simulation:
    depends_on:
      prepare:
        condition: service_completed_successfully
      populate-db:
        condition: service_completed_successfully
      start-db:
        condition: service_started
      download-dataset:
        condition: service_completed_successfully
    image: danysk/${PROJECT_NAME:-unknown}-simulation:${VERSION:-latest}
    build:
      dockerfile: ./docker/sim/Dockerfile
      context: .
    volumes:
     - ./PM10-summary:/experiment/PM10-summary:rw

  charts:
    depends_on:
      prepare:
        condition: service_completed_successfully
      simulation:
        condition: service_completed_successfully
    image: danysk/${PROJECT_NAME:-unknown}-charts:${VERSION:-latest}
    build:
      dockerfile: ./docker/charts/Dockerfile
      context: .
    volumes:
      - ./data:/experiment/data
      - ./charts:/experiment/charts

  finish:
    depends_on:
      charts:
        condition: service_completed_successfully
    image: alpine:3.17.3
    volumes:
      - .:/experiment:rw
    entrypoint: /bin/sh -c
    command:
      - |
        find /experiment/data -type d -exec chmod 777 {} \;
        find /experiment/charts -type d -exec chmod 777 {} \;
        find /experiment/data -type f -exec chmod 666 {} \;
        find /experiment/charts -type f -exec chmod 666 {} \;
